### ISSUE TITLE
After 1 hour from the completion of authentication, the response  not return

### ISSUE THREAD

**Issue by ShuheiOno** [microsoftgraph/msgraph-sdk-ios#31]
Hi

I login from my app using `NXOAuth2AuthenticationProvider.sharedAuth().login~`.
After authenticate, my app can access OneDrive.

But when it passes just one hour from authentication, I execute  `self.graphClient.me().request().getWithCompletion`, I get no response.
It occurs after 1 hour from the completion of authentication, I guess it relate to access token expire.

Is there any solutions?

**Comment by caitlinrussell** [comment]
You are correct that the token has expired. You will need to use your refresh token to get a new access token. I would suggest asking your question on StackOverflow. Otherwise, your question would make more sense on the [Microsoft Graph iOS Auth Adapter repo](https://github.com/microsoftgraph/msgraph-sdk-ios-nxoauth2-adapter) since this is the piece that handles auth.
