### ISSUE TITLE
Sharepoint site drive

### ISSUE THREAD

**Issue by apognu** [microsoftgraph/msgraph-sdk-ios#9]
Hi there,

I couldn't find a way to get the folders and file in a specific Sharepoint site, or a way to list all available sites. Is this available? If it is, could you give me a pointer on how to proceed?

For now I'm only able to get the content of a user's personal drive and Sharepoint's "default" site.

Regards.

**Comment by unpluggedk** [comment]
The API you are referring to is included in the beta endpoint. 
Please refer to this [document](http://graph.microsoft.io/en-us/docs/api-reference/beta/resources/sharepoint).

Unfortunately, the current version of the SDK only works for v1 endpoints, so for this to work, you have to use the REST approach for now until this is fixed in the SDK.

Thanks and sorry for the inconvenience.

**Comment by jasonjoh** [comment]
This project is being archived and replaced with the [Microsoft Graph SDK for ObjC](https://github.com/microsoftgraph/msgraph-sdk-objc). As part of the archival process, we're closing all open issues and pull requests. See #37 for more context.

You can continue to use this library "as-is", but it won't be maintained moving forward. We apologize for any inconvenience.
